# Generated by Django 2.1.1 on 2018-09-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='image',
            new_name='photo',
        ),
    ]
